# Generated by Django 4.2.6 on 2023-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя с фамилией')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
            ],
        ),
    ]
