# Generated by Django 4.2.6 on 2023-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, upload_to='team_members_img', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
